import type { AbilityDef } from '../types';

/** Retained Talents V2 active grants: Mage, Warlock, and Druid. */
export const TALENT_ABILITIES_V2_B = {
  spellsteal: {
    id: 'spellsteal',
    name: 'Spellsteal',
    class: 'mage',
    learnLevel: 8,
    cost: 40,
    castTime: 0,
    cooldown: 12,
    range: 30,
    school: 'arcane',
    requiresTarget: true,
    targetType: 'any',
    effects: [{ type: 'dispel', count: 1, steal: true }],
    description: 'Steals a beneficial magic effect from an enemy, transferring it to yourself.',
  },
  cone_of_cold: {
    id: 'cone_of_cold',
    name: 'Frostsweep',
    class: 'mage',
    learnLevel: 10,
    cost: 60,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'frost',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 28, max: 36, radius: 8 }],
    description: 'Blasts nearby enemies with frost for $d Frost damage. (Frost signature)',
  },
  presence_of_mind: {
    id: 'presence_of_mind',
    name: 'Racing Mind',
    class: 'mage',
    learnLevel: 5,
    cost: 0,
    castTime: 0,
    cooldown: 60,
    range: 0,
    school: 'arcane',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'next_cast_instant', value: 1, duration: 60 }],
    description: 'Makes your next spell with a cast time instant. Lasts 60 sec. (Mage talent)',
  },
  blink: {
    id: 'blink',
    name: 'Flickerstep',
    class: 'mage',
    learnLevel: 5,
    cost: 40,
    castTime: 0,
    cooldown: 15,
    range: 0,
    school: 'arcane',
    requiresTarget: false,
    effects: [{ type: 'blinkForward', distance: 15, breakRoots: true }],
    description: 'Teleports you 15 yd forward and breaks roots. (Mage talent)',
  },
  ice_block: {
    id: 'ice_block',
    name: 'Cold Coffin',
    class: 'mage',
    learnLevel: 5,
    cost: 15,
    castTime: 0,
    cooldown: 240,
    range: 0,
    school: 'frost',
    requiresTarget: false,
    effects: [
      { type: 'absorb', amount: 600, duration: 8 },
      { type: 'selfBuff', kind: 'stasis', value: 0, duration: 8 },
    ],
    description:
      'Encases you in ice, absorbing 600 damage for 8 sec. You cannot act while encased. Recast to cancel. (Mage talent)',
  },
  deep_freeze: {
    id: 'deep_freeze',
    name: 'Deadfrost',
    class: 'mage',
    learnLevel: 5,
    cost: 60,
    castTime: 0,
    cooldown: 30,
    range: 30,
    school: 'frost',
    requiresTarget: true,
    effects: [
      { type: 'directDamage', min: 92, max: 116 },
      { type: 'stun', duration: 4 },
    ],
    description:
      'Deep freezes the target, dealing $d Frost damage and stunning it for 4 sec. (Mage talent)',
  },
  meteor: {
    id: 'meteor',
    name: 'Skystone',
    class: 'mage',
    learnLevel: 5,
    cost: 120,
    castTime: 0,
    cooldown: 45,
    range: 30,
    school: 'fire',
    requiresTarget: false,
    targetMode: 'position',
    effects: [
      { type: 'aoeDamage', min: 100, max: 130, radius: 8 },
      { type: 'groundAoE', min: 12, max: 18, radius: 8, duration: 6, interval: 2 },
    ],
    description:
      'Calls down a meteor at the target area, dealing $d Fire damage, then burning enemies there for 12 to 18 Fire damage every 2 sec for 6 sec. (Mage talent)',
  },
  evocation: {
    id: 'evocation',
    name: 'Aetherwell',
    class: 'mage',
    learnLevel: 5,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'arcane',
    requiresTarget: false,
    effects: [{ type: 'gainResource', amount: 220 }],
    description: 'Instantly restores 220 mana. (Mage talent)',
  },

  voidfeast: {
    id: 'voidfeast',
    name: 'Voidfeast',
    class: 'warlock',
    learnLevel: 8,
    cost: 35,
    castTime: 0,
    cooldown: 15,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    targetType: 'any',
    effects: [
      { type: 'dispel', count: 1 },
      { type: 'selfHealPctMax', pct: 0.06 },
    ],
    description:
      'Devours a magic effect (a beneficial one from an enemy, or a harmful one from an ally) and heals you for 6% of your maximum health.',
  },
  howl_of_terror: {
    id: 'howl_of_terror',
    name: 'Dread Chorus',
    class: 'warlock',
    learnLevel: 10,
    cost: 55,
    castTime: 0,
    cooldown: 40,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'aoeFear', duration: 3, radius: 8 }],
    description:
      'Frightens nearby enemies for up to 3 sec. Damage may break the effect. (Warlock talent)',
  },
  curse_of_exhaustion: {
    id: 'curse_of_exhaustion',
    name: 'Leaden Hex',
    class: 'warlock',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'slow', mult: 0.7, duration: 12 }],
    description: 'Curses the target, slowing movement by 30% for 12 sec. (Warlock talent)',
  },
  death_coil: {
    id: 'death_coil',
    name: 'Morrowlash',
    class: 'warlock',
    learnLevel: 10,
    cost: 70,
    castTime: 0,
    cooldown: 120,
    range: 20,
    school: 'shadow',
    requiresTarget: true,
    fearDr: true,
    effects: [
      { type: 'directDamage', min: 55, max: 65 },
      { type: 'incapacitate', duration: 3 },
    ],
    description:
      'Strikes the enemy for $d Shadow damage, then horrifies them for 3 sec. (Warlock talent)',
  },
  chaos_bolt: {
    id: 'chaos_bolt',
    name: 'Ruinbolt',
    class: 'warlock',
    learnLevel: 10,
    cost: 95,
    castTime: 2.5,
    cooldown: 12,
    range: 30,
    school: 'fire',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 128, max: 156 }],
    description: 'Hurls a bolt of chaotic fire for $d Fire damage. (Warlock talent)',
  },

  typhoon: {
    id: 'typhoon',
    name: 'Typhoon',
    class: 'druid',
    learnLevel: 8,
    cost: 30,
    castTime: 0,
    cooldown: 20,
    range: 0,
    requiresTarget: false,
    school: 'nature',
    effects: [{ type: 'aoeKnockback', radius: 8, distance: 6, dazeMult: 0.5, dazeDuration: 4 }],
    description:
      'A blast of wind knocks back all enemies within 8 yd and dazes them, slowing their movement by 50% for 4 sec.',
  },
  innervate: {
    id: 'innervate',
    name: 'Lifesap',
    class: 'druid',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    usableInForm: true,
    effects: [{ type: 'selfBuff', kind: 'resource_sap', value: 20, duration: 10 }],
    description:
      'Living sap wells up in you for 10 sec, restoring 20 of your current resource in waves: mana, Rage, or Energy, and shifting forms does not break it. Sleep, stun, or stasis stills the sap. (Druid talent)',
  },
  frenzied_regeneration: {
    id: 'frenzied_regeneration',
    name: 'Savage Mending',
    class: 'druid',
    learnLevel: 10,
    cost: 10,
    castTime: 0,
    cooldown: 60,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    requiresForm: 'bear',
    effects: [{ type: 'hot', total: 180, duration: 10, interval: 2 }],
    description: 'Restores 180 health over 10 sec. Bruin Form only. (Druid talent)',
  },
  berserk: {
    id: 'berserk',
    name: 'Red Haze',
    class: 'druid',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 180,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    usableInForm: true,
    effects: [{ type: 'selfBuff', kind: 'buff_ap', value: 70, duration: 15 }],
    description: 'Increases attack power by 70 for 15 sec. (Druid talent)',
  },
  tranquility: {
    id: 'tranquility',
    name: 'Gladesong',
    class: 'druid',
    learnLevel: 10,
    cost: 120,
    castTime: 0,
    channel: { duration: 4, ticks: 4 },
    cooldown: 300,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 42, max: 52, radius: 30 }],
    description:
      'Channels restorative energy for 4 sec, healing allies within 30 yd for 42 to 52 each second. (Druid talent)',
  },
} satisfies Record<string, AbilityDef>;
